import { ExternalLink } from "lucide-react";

const projects = [
  {
    title: "MemoryStones",
    url: "https://github.com/anugrahnm/memory-stones",
    description:
      "Cross-platform performance study comparing Flutter and React Native through two functionally identical memory games with custom diagnostic tooling.",
    bullets: [
      "Designed and implemented custom in-app diagnostic tooling to measure tap-to-render interaction latency, frame timing, and jank detection across 60Hz gameplay sessions.",
      "Integrated Firebase Performance Monitoring for standardised startup time tracking and interaction timing traces, validated against Flutter DevTools and Xcode Instruments.",
      "Results showed Flutter had lower interaction latency and more stable frame delivery, while React Native achieved faster startup and lower memory usage.",
    ],
    skills: ["Flutter", "Dart", "React Native", "TypeScript", "Firebase"],
  },
  {
    title: "Data Summarizer",
    url: "https://summarizer.anugrah.dev",
    description:
      "AI-powered document summarisation tool. Upload a PDF or plain text file and get a structured summary generated by Google Gemini.",
    bullets: [
      "Built with Python and Streamlit, integrating the Google Gemini API for intelligent document summarisation.",
      "Supports PDF and plain text input with clean structured output, deployed live on Streamlit Cloud.",
    ],
    skills: ["Python", "Streamlit", "Google Gemini API"],
  },
  {
    title: "Shortlist",
    url: "https://shortlist.anugrah.dev",
    description:
      "CV to job description matching tool with TF-IDF and Gemini AI modes.",
    bullets: [
      "Built a full-stack CV matching tool with two modes: TF-IDF cosine similarity for fast keyword matching and Google Gemini 3.1 Flash Lite for semantic analysis with URL scraping. Supports CV upload with PDF text extraction via PyMuPDF.",
      "Deployed on a DigitalOcean VPS with Docker, Caddy reverse proxy, and GitHub Actions CI/CD. Frontend built with Vue 3, Vite, and TypeScript.",
    ],
    skills: [
      "Vue 3",
      "TypeScript",
      "FastAPI",
      "Python",
      "scikit-learn",
      "Gemini API",
      "PyMuPDF",
      "Docker",
      "DigitalOcean",
    ],
  },
  {
    title: "PyReminder API",
    url: "https://pyreminder-api-production.up.railway.app/docs",
    description:
      "A production REST API with authentication for managing reminders, built with FastAPI and PostgreSQL.",
    bullets: [
      "Implemented JWT-based authentication and full CRUD operations for reminder management with a PostgreSQL backend.",
      "Deployed on Railway with auto-generated OpenAPI/Swagger documentation.",
    ],
    skills: ["Python", "FastAPI", "PostgreSQL", "JWT", "Railway"],
  },
  {
    title: "TaskFlow",
    url: "https://github.com/anugrahnm/taskflow",
    description:
      "Full-stack task management application using Next.js and Supabase with real-time sync.",
    bullets: [
      "Implemented Supabase Auth with Row Level Security (RLS) to ensure secure, isolated user data access and encrypted session management.",
      "Utilized PostgreSQL Realtime replication to synchronize task updates across the UI via WebSockets, eliminating manual page refreshes.",
      "Optimized frontend performance using TypeScript and Tailwind CSS, achieving a 95+ score on Google Lighthouse.",
    ],
    skills: ["Next.js", "Supabase", "PostgreSQL", "TypeScript", "Tailwind CSS"],
  },
];

export function Projects() {
  return (
    <section id="projects" className="px-6 py-24 lg:py-32">
      <div className="mx-auto max-w-5xl">
        <SectionHeader number="03" title="projects" />
        <div className="mt-12 grid gap-6 sm:grid-cols-1">
          {projects.map((project) => (
            <a
              key={project.title}
              href={project.url}
              target="_blank"
              rel="noopener noreferrer"
              className="group flex flex-col rounded-xl border border-border bg-card p-6 transition-all hover:border-primary/30 hover:bg-card/80"
            >
              <h3 className="flex items-center gap-2 font-semibold text-foreground">
                {project.title}
                <ExternalLink className="h-3.5 w-3.5 text-primary opacity-0 transition-all group-hover:opacity-100 group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
              </h3>
              <p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">
                {project.description}
              </p>
              <ul className="mt-4 flex flex-col gap-1.5">
                {project.bullets.map((bullet) => (
                  <li
                    key={bullet}
                    className="flex items-start gap-2 text-sm leading-relaxed text-muted-foreground"
                  >
                    <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-primary" />
                    {bullet}
                  </li>
                ))}
              </ul>
              <div className="mt-5 flex flex-wrap gap-2">
                {project.skills.map((skill) => (
                  <span
                    key={skill}
                    className="rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary"
                  >
                    {skill}
                  </span>
                ))}
              </div>
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}

function SectionHeader({ number, title }: { number: string; title: string }) {
  return (
    <div className="flex items-center gap-4">
      <span className="font-mono text-sm text-primary/60">{number}</span>
      <h2 className="text-2xl font-bold uppercase tracking-tight text-foreground sm:text-3xl">
        <span className="font-mono text-muted-foreground">{"// "}</span>
        {title}
      </h2>
      <span className="hidden h-px flex-1 bg-border sm:block" />
    </div>
  );
}
